version: '3.3'

services:
    backendapp:
      container_name: backendapp
      build: ./backend
      ports:
        - "3000:3000"
      volumes:
        - ./backend:/usr/src/app
      depends_on:
        - postgres
    frontendapp:
      container_name: frontendapp
      build: ./frontend
      ports:
        - "5000:5000"
      volumes:
        - ./frontend:/usr/src/app
      depends_on:
        - backendapp
    postgres:
      image: postgres:13
      restart: always
      environment:
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_DB=my_store
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
      ports:
        - 5432:5432
      volumes:
        - ./backend/postgres_data:/var/lib/postgresql/data
      logging:
        driver: none
    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "80:80"
      depends_on:
        - postgres
      logging:
        driver: none